gitRepo = "https://github.com/jerdog/jmeiss-me-toha"

[features.portfolio]
enable = true

  [features.portfolio.blog]
  enable = true

  [features.portfolio.toc]
  enable = true

[features.blog]
enable = true
showAuthor = true

[footer]
enable = true
