#gitRepo = "https://github.com/jerdog/jmeiss-me-toha"
background = "images/background.jpg"

[logo]
main = "images/me.png"
inverted = "images/me.png"
favicon = "images/fav.png"

[features.tags]
enable = true
on_card = true

[features.readingTime]
enable = true

[features.analytics]
enable = true

[features.analytics.services.google]
id = "G-7LJ0M7K1R6"

[features.portfolio]
enable = true

  [features.portfolio.blog]
  enable = true

  [features.portfolio.toc]
  enable = true

[features.blog]
enable = true
showAuthor = true

  [features.blog.shareButtons]
  facebook = true
  twitter = true
  linkedin = true
  reddit = true

[features.toc]
enable = true

[features.pagination]
maxPostsPerPage = 9

[footer]
enable = true

    [footer.navigation]
    enable = true
    customMenus = true

    [footer.contactMe]
    enable = true

    [footer.credentials]
    enable = true

    [footer.newsletter]
    enable = false
    provider = "mailchimp"
    mailchimpURL = ""

    [footer.disclaimer]
    enable = true
