gitRepo = "https://github.com/jerdog/jmeiss-me-toha"
background = "images/background.jpg"

[logo]
main = "images/avatar.png"
#inverted = "images/inverted-logo.png"
favicon = "images/fav.png"

[features.portfolio]
enable = true

  [features.portfolio.blog]
  enable = true

  [features.portfolio.toc]
  enable = true

[features.blog]
enable = true
showAuthor = true

[footer]
enable = true
