baseURL = 'https://jmeiss-me-toha.netlify.app/'
languageCode = 'en-us'
title = 'Jeremy Meiss | DevEx Professional'
enableEmoji = true

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 6
ordered = false

[outputs]
home = [ "HTML", "RSS", "JSON" ]
