baseURL = 'https://jmeiss-me-toha.netlify.app/'
languageCode = 'en-us'
title = 'Jeremy Meiss'
enableEmoji = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.renderHooks]
            [markup.goldmark.renderHooks.link]
                enableDefault = true
[markup.tableOfContents]
    startLevel = 2
    endLevel = 6
    ordered = false

[outputs]
home = [ "HTML", "RSS", "JSON", "TXT" ]
page = [ "HTML", "TXT" ]

[outputFormats]
    [outputFormats.TXT]
    name = "text"
    baseName = "text"
    mediaType = "text/plain"
    isHTML = false
    isPlainText = true
    noUgly = true
    permalinkable = true

[mediaTypes]
  [mediaTypes."text/plain"]
    suffix = "txt"

