[build]
    command = "hugo --gc --minify --buildFuture && cp static/keybase.txt public/"
    publish = "public"

[context.production.environment]
    HUGO_ENABLEGITINFO = "true"
    HUGO_ENV           = "production"
    HUGO_VERSION       = "0.124.1"
    NODE_VERSION       = "v18.12.1"
    NPM_VERSION        = "8.19.2"
    GO_VERSION         = "1.22.3"

[context.split1]
command = "hugo mod tidy && hugo mod npm pack && npm install && hugo --gc --minify --enableGitInfo && cp static/keybase.txt public/"

    [context.split1.environment]
    HUGO_ENV     = "production"
    HUGO_VERSION = "0.124.1"
    NODE_VERSION = "v18.12.1"
    NPM_VERSION  = "8.19.2"
    GO_VERSION   = "1.22.3"

[context.deploy-preview]
command = "hugo mod tidy && hugo mod npm pack && npm install && hugo --gc --minify --buildDrafts --buildFuture -b $DEPLOY_PRIME_URL && cp static/keybase.txt public/"

    [context.deploy-preview.environment]
    HUGO_VERSION = "0.124.1"
    NODE_VERSION = "v18.12.1"
    NPM_VERSION  = "8.19.2"
    GO_VERSION   = "1.22.3"

[context.branch-deploy]
command = "hugo mod tidy && hugo mod npm pack && npm install && hugo --gc --minify --buildDrafts --buildFuture -b $DEPLOY_PRIME_URL && cp static/keybase.txt public/"

    [context.branch-deploy.environment]
    HUGO_VERSION = "0.124.1"
    NODE_VERSION = "v18.12.1"
    NPM_VERSION  = "8.19.2"
    GO_VERSION   = "1.22.3"

[context.next.environment]
    HUGO_ENABLEGITINFO = "true"